// <auto-generated />
using System;
using CJTimbangan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CJTimbangan.Migrations
{
    [DbContext(typeof(SettingTimbanganContext))]
    [Migration("20191112044000_CJTimbangan")]
    partial class CJTimbangan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CJTimbangan.Models.Input", b =>
                {
                    b.Property<int>("id_transaksi")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("barang");

                    b.Property<int>("counter");

                    b.Property<string>("id_controller");

                    b.Property<string>("id_dig_scale");

                    b.Property<string>("id_printer");

                    b.Property<string>("kemasan");

                    b.Property<string>("location");

                    b.Property<string>("lot_no");

                    b.Property<int>("reprint");

                    b.Property<int>("shift");

                    b.Property<string>("status");

                    b.Property<float>("tare");

                    b.Property<DateTime>("tgl_cetak");

                    b.Property<DateTime>("tgl_produksi");

                    b.Property<string>("type_controller");

                    b.Property<string>("type_dig_scale");

                    b.Property<string>("type_printer");

                    b.Property<float>("weight");

                    b.HasKey("id_transaksi");

                    b.ToTable("m_hasil");
                });

            modelBuilder.Entity("CJTimbangan.Models.Setting", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("barang");

                    b.Property<string>("code");

                    b.Property<int>("counter");

                    b.Property<string>("id_controller");

                    b.Property<string>("id_dig_scale");

                    b.Property<string>("id_printer");

                    b.Property<string>("ip_controller");

                    b.Property<string>("ip_printer");

                    b.Property<string>("kemasan");

                    b.Property<string>("location");

                    b.Property<string>("lot_no");

                    b.Property<string>("path");

                    b.Property<double>("tare");

                    b.Property<string>("type_controller");

                    b.Property<string>("type_dig_scale");

                    b.Property<string>("type_printer");

                    b.HasKey("id");

                    b.ToTable("m_code");
                });
#pragma warning restore 612, 618
        }
    }
}
